name: Build Linux

on:
  push:
    branches:  
    - '*'
  pull_request:
    branches:  
    - '*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd scripts
        ./build_linux.sh
